import { createContext, useContext, useState, useCallback, ReactNode } from 'react'

export type Lang = 'en' | 'es' | 'fr' | 'de' | 'pt' | 'ru'

interface LangContextValue {
  lang: Lang
  setLang: (l: Lang) => void
  t: (key: string, vars?: Record<string, string | number>) => string
}

const LangContext = createContext<LangContextValue>(null!)

export function useLang() {
  return useContext(LangContext)
}

// ─── Translations ───
const translations: Record<Lang, Record<string, string>> = {
  en: {
    // Nav
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.products': 'Products',
        'nav.blog': 'Blog',
    'nav.videos': 'Videos',
    'videos.heroTag': 'Video Gallery',
    'videos.heroTitle': 'See Our Craft in Motion',
    'videos.heroDesc': 'Watch our premium knitwear come to life - from product showcases to the craftsmanship behind every sweater.',
    'videos.all': 'All',
    'videos.product': 'Product',
    'videos.brand': 'Brand',
    'videos.noVideos': 'No videos available yet. Check back soon!',
    'videos.ctaTitle': 'Want to Learn More?',
    'videos.ctaDesc': 'Contact us for product details, wholesale inquiries, or to see our collection in person.',
    'videos.contactBtn': 'Contact Us',
    'videos.viewProducts': 'View Products',
    'nav.contact': 'Contact',
    'nav.amazonStore': 'Amazon Store',
    'nav.getQuote': 'Get a Quote',

    // Footer
    'footer.quickLinks': 'Quick Links',
    'footer.collections': 'Collections',
    'footer.contact': 'Contact',
    'footer.rights': 'All rights reserved.',
    'footer.brandDesc': 'Premium knitwear manufacturer dedicated to crafting exceptional sweaters, cardigans, and knit tops for the global fashion industry.',
    'footer.menSweaters': "Men's Sweaters",
    'footer.womenSweaters': "Women's Sweaters",
    'footer.cashmere': 'Cashmere Collection',
    'footer.merino': 'Merino Wool',

    // Home
    'home.featuredSubtitle': 'Featured Collection',
    'home.featuredTitle': 'Our Signature Knitwear',
    'home.featuredDesc': 'Explore our curated selection of premium wool sweaters.',
    'home.viewAll': 'View All Products',
    'home.whyUs': 'Why LINFAIR',
    'home.whyUsTitle': 'Why Choose Us',
    'home.whyUsDesc': 'What sets our knitwear apart.',
    'home.ctaTitle': 'Ready to Source Premium Knitwear?',
    'home.ctaDesc': 'Partner with LINFAIR for your next collection. Contact us for a consultation and quote.',
    'home.ctaBtn': 'Get in Touch',

    // About
    'about.valuesSubtitle': 'Our Values',
    'about.valuesTitle': 'What We Stand For',
    'about.valuesDesc': 'The principles that guide every sweater we make.',
    'about.timelineSubtitle': 'Our Journey',
    'about.timelineTitle': 'Milestones',
    'about.timelineDesc': 'Key moments in our evolution as a premium knitwear manufacturer.',
    'about.ctaTitle': 'Start Your Partnership',
    'about.ctaDesc': "Let's create exceptional knitwear for your brand. Get in touch with our team.",
    'about.ctaBtn': 'Contact Us',

    // Products
    'products.heroSubtitle': 'Products',
    'products.heroTitle': 'Our Knitwear',
    'products.heroHighlight': 'Collection',
    'products.heroDesc': "Premium women's knitwear crafted for comfort and style. Each piece available in multiple colors.",
    'products.all': 'All',
    'products.inquire': 'Inquire Now',
    'products.inquireAbout': 'Inquire About This Product',
    'products.requestQuote': 'Request a Quote',
    'products.specs': 'Specifications',
    'products.video': 'Watch Video',
    'products.photos': 'Photos',
    'products.noProducts': 'No products found in this category.',
    'products.ctaTitle': 'Need Custom Knitwear?',
    'products.ctaDesc': "We develop custom sweaters tailored to your brand's specifications. Let's create something together.",
    'products.ctaBtn': 'Request a Quote',
    'products.articlesSubtitle': 'From Our Blog',
    'products.articlesTitle': 'Latest Articles',
    'products.viewAllArticles': 'View All Articles',
    'products.readArticle': 'Read Article',

    // Blog
    'blog.heroSubtitle': 'Blog',
    'search.placeholder': 'Search...',
    'search.products': 'Products',
    'search.articles': 'Articles',
    'search.empty': 'Type to search products and articles',
    'search.noResults': 'No results found',
    'blog.heroTitle': 'Insights &',
    'blog.heroHighlight': 'Trends',
    'blog.heroDesc': 'Stay informed with the latest in knitwear fashion, sourcing tips, and industry insights from LINFAIR Wool.',
    'blog.readMore': 'Read More',
    'blog.ctaTitle': 'Stay in the Loop',
    'blog.ctaDesc': 'Subscribe to receive the latest knitwear trends, sourcing tips, and company updates directly to your inbox.',
    'blog.ctaBtn': 'Contact Us to Subscribe',
    'blog.back': 'Back to Blog',
    'blog.notFound': 'Post Not Found',
    'blog.notFoundDesc': 'The blog post you are looking for does not exist.',
    'blog.backBtn': 'Back to Blog',
    'blog.relatedTitle': 'Interested in Working With Us?',
    'blog.relatedDesc': 'Whether you have a specific project in mind or just want to explore possibilities, we would love to hear from you.',
    'blog.contactBtn': 'Contact Us',
    'blog.viewProducts': 'View Products',

    // Contact
    'contact.formName': 'Name',
    'contact.formEmail': 'Email',
    'contact.formCompany': 'Company',
    'contact.formSubject': 'Subject',
    'contact.formMessage': 'Message',
    'contact.formPlaceholderName': 'Your name',
    'contact.formPlaceholderEmail': 'your@email.com',
    'contact.formPlaceholderCompany': 'Your company name',
    'contact.formPlaceholderSubject': 'How can we help?',
    'contact.formPlaceholderMessage': 'Tell us about your knitwear requirements...',
    'contact.formSubmit': 'Send Message',
    'contact.formSending': 'Sending...',
    'contact.formRequired': 'is required',
    'contact.formInvalidEmail': 'Invalid email format',
    'contact.thankYou': 'Thank You!',
    'contact.thankYouMsg': 'Your message has been sent. We will get back to you within 24 hours.',
    'contact.sendAnother': 'Send Another Message',
    'contact.infoTitle': 'Contact Information',
    'contact.address': 'Address',
    'contact.email': 'Email',
    'contact.phone': 'Phone',
    'contact.whatsapp': 'Chat on WhatsApp',
    'contact.hours': 'Business Hours',

    // Admin
    'admin.title': 'LINFAIR Admin Panel',
    'admin.viewSite': 'View Site',
    'admin.export': 'Export Data',
    'admin.save': 'Save Changes',
    'admin.saving': 'Saving...',
    'admin.logout': 'Logout',
    'admin.tabProducts': 'Products',
    'admin.tabBlog': 'Blog',
    'admin.tabContent': 'Page Content',
    'admin.tabInquiries': 'Inquiries',
    'admin.reset': 'Reset Default',
    'admin.addProduct': '+ Add Product',
    'admin.addBlog': '+ Add Article',
    'admin.saveSuccess': 'Saved successfully!',
    'admin.saveLocal': 'Saved to local storage.',
    'admin.loading': 'Loading...',
    'admin.import': 'Import',
    'admin.galleryImages': 'Gallery Images ({count} / 5)',
    'admin.galleryHint': 'Click + to add images (max 5). Hover over an image to remove it.',
    'admin.specs': 'Specs (one per line)',
    'admin.videoUrl': 'Video URL (YouTube embed link, optional)',
    'admin.content': 'Content (Markdown supported)',
    'admin.paragraphsOnePerLine': 'Paragraphs (one per line)',
    'admin.paragraphsBlankLine': 'Paragraphs (blank line separated)',
    'admin.contactPage': 'Contact - Page Content',
    'admin.socialHint': 'Manage social media icons displayed in header and footer. Uncheck to hide.',
    'admin.uploadImage': '+ Upload Local Image',
    'admin.loadFailed': 'Failed to load data',
    'admin.newAdvantage': 'New Advantage',
    'admin.newValue': 'New Value',
    'admin.newMilestone': 'New Milestone',
    'admin.newCategory': 'New Category',
    'admin.newPlatform': 'New Platform',
    'admin.newPage': 'New Page',
    'admin.confirmDeleteProduct': 'Delete this product?',
    'admin.confirmDeletePost': 'Delete this post?',
    'admin.placeholderImageUrl': '图片URL或上传本地图片',
    'admin.placeholderVideoUrl': 'https://www.youtube.com/embed/...',
    'admin.placeholderBlogContent': '在此编写博客内容... 支持 Markdown: ## 标题, - 列表, **加粗**',
    'admin.placeholderSocialUrl': 'https://...',
    'admin.placeholderLabel': '名称',
    'admin.placeholderPath': '/路径',
    'admin.altPreview': '预览',
    'admin.titleImport': '从文件导入数据',
    'admin.titleExport': '导出数据文件',
    'admin.titleDelete': '删除',
    'admin.homeHero': 'Home - Hero Section',
    'admin.aboutHero': 'About - Hero Section',
    'admin.resetConfirm': 'Are you sure you want to reset to default data? All changes will be lost.',
    'admin.productName': 'Product Name',
    'admin.category': 'Category',
    'admin.subcategory': 'Subcategory',
    'admin.excerpt': 'Excerpt',
    'admin.date': 'Date',
    'admin.description': 'Description',
    'admin.statistics': 'Statistics',
    'admin.brandStory': 'Brand Story',
    'admin.advantages': 'Advantages',
    'admin.ctaSection': 'CTA Section',
    'admin.companyIntro': 'Company Intro',
    'admin.coreValues': 'Core Values',
    'admin.timeline': 'Timeline',
    'admin.socialLinks': 'Social Media Links',
    'admin.confirmReset': 'Confirm Reset',
    'admin.name': 'Name',
    'admin.email': 'Email',
    'admin.company': 'Company',
    'admin.submitted': 'Submitted',
    'admin.message': 'Message',
    'admin.noInquiries': 'No inquiries yet',

    // Language
    'lang.en': 'English',
    'lang.es': 'Español',
    'lang.fr': 'Français',
    'lang.de': 'Deutsch',
    'lang.pt': 'Português',
    'lang.ru': 'Русский',
  },

  es: {
    'nav.home': 'Inicio',
    'nav.about': 'Nosotros',
    'nav.products': 'Productos',
        'nav.blog': 'Blog',
    'nav.videos': 'Vídeos',
    'videos.heroTag': 'Galería de Vídeos',
    'videos.heroTitle': 'Mira Nuestra Artesanía en Movimiento',
    'videos.heroDesc': 'Mira nuestra ropa de punto premium cobrar vida - desde muestras de productos hasta la artesanía detrás de cada suéter.',
    'videos.all': 'Todo',
    'videos.product': 'Producto',
    'videos.brand': 'Marca',
    'videos.noVideos': 'Aún no hay vídeos disponibles. ¡Vuelve pronto!',
    'videos.ctaTitle': '¿Quieres Saber Más?',
    'videos.ctaDesc': 'Contáctanos para detalles de productos, consultas al por mayor o para ver nuestra colección en persona.',
    'videos.contactBtn': 'Contáctanos',
    'videos.viewProducts': 'Ver Productos',
    'nav.contact': 'Contacto',
    'nav.getQuote': 'Solicitar Cotización',
    'footer.quickLinks': 'Enlaces Rápidos',
    'footer.collections': 'Colecciones',
    'footer.contact': 'Contacto',
    'footer.rights': 'Todos los derechos reservados.',
    'footer.brandDesc': 'Fabricante premium de prendas de punto dedicado a crear suéteres, cárdigans y tops de punto excepcionales para la industria global de la moda.',
    'footer.menSweaters': 'Suéteres de Hombre',
    'footer.womenSweaters': 'Suéteres de Mujer',
    'footer.cashmere': 'Colección de Cachemira',
    'footer.merino': 'Lana Merino',
    'home.featuredSubtitle': 'Colección Destacada',
    'home.featuredTitle': 'Nuestros Tejidos Emblemáticos',
    'home.featuredDesc': 'Explore nuestra selección curada de suéteres de lana premium.',
    'home.viewAll': 'Ver Todos los Productos',
    'home.whyUs': 'Por Qué LINFAIR',
    'home.whyUsTitle': 'Por Qué Elegirnos',
    'home.whyUsDesc': 'Lo que hace que nuestros tejidos sean únicos.',
    'home.ctaTitle': '¿Listo para adquirir prendas de punto premium?',
    'home.ctaDesc': 'Asóciese con LINFAIR para su próxima colección. Contáctenos para una consulta y cotización.',
    'home.ctaBtn': 'Póngase en Contacto',
    'about.valuesSubtitle': 'Nuestros Valores',
    'about.valuesTitle': 'Lo Que Defendemos',
    'about.valuesDesc': 'Los principios que guían cada suéter que hacemos.',
    'about.timelineSubtitle': 'Nuestra Trayectoria',
    'about.timelineTitle': 'Hitos',
    'about.timelineDesc': 'Momentos clave en nuestra evolución como fabricante premium de prendas de punto.',
    'about.ctaTitle': 'Comience su Asociación',
    'about.ctaDesc': 'Creemos prendas de punto excepcionales para su marca. Comuníquese con nuestro equipo.',
    'about.ctaBtn': 'Contáctenos',
    'products.heroSubtitle': 'Productos',
    'products.heroTitle': 'Nuestros Tejidos',
    'products.heroHighlight': 'Colección',
    'products.heroDesc': 'Prendas de punto premium para mujer, creadas para la comodidad y el estilo. Cada pieza disponible en múltiples colores.',
    'products.all': 'Todos',
    'products.inquire': 'Consultar Ahora',
    'products.inquireAbout': 'Consultar Sobre Este Producto',
    'products.requestQuote': 'Solicitar Cotización',
    'products.specs': 'Especificaciones',
    'products.video': 'Ver Video',
    'products.photos': 'Fotos',
    'products.noProducts': 'No se encontraron productos en esta categoría.',
    'products.ctaTitle': '¿Necesita prendas de punto personalizadas?',
    'products.ctaDesc': 'Desarrollamos suéteres personalizados según las especificaciones de su marca. Creemos algo juntos.',
    'products.ctaBtn': 'Solicitar Cotización',
    'products.articlesSubtitle': 'De Nuestro Blog',
    'products.articlesTitle': 'Últimos Artículos',
    'products.viewAllArticles': 'Ver Todos los Artículos',
    'products.readArticle': 'Leer Artículo',
    'blog.heroSubtitle': 'Blog',
    'search.placeholder': 'Buscar...',
    'search.products': 'Productos',
    'search.articles': 'Artículos',
    'search.empty': 'Escribe para buscar productos y artículos',
    'search.noResults': 'No se encontraron resultados',
    'blog.heroTitle': 'Perspectivas y',
    'blog.heroHighlight': 'Tendencias',
    'blog.heroDesc': 'Manténgase informado con lo último en moda de punto, consejos de abastecimiento y perspectivas de la industria de LINFAIR Wool.',
    'blog.readMore': 'Leer Más',
    'blog.ctaTitle': 'Manténgase al Día',
    'blog.ctaDesc': 'Suscríbase para recibir las últimas tendencias en prendas de punto, consejos de abastecimiento y actualizaciones de la empresa directamente en su bandeja de entrada.',
    'blog.ctaBtn': 'Contáctenos para Suscribirse',
    'blog.back': 'Volver al Blog',
    'blog.notFound': 'Artículo No Encontrado',
    'blog.notFoundDesc': 'El artículo que busca no existe.',
    'blog.backBtn': 'Volver al Blog',
    'blog.relatedTitle': '¿Interesado en Trabajar con Nosotros?',
    'blog.relatedDesc': 'Ya sea que tenga un proyecto específico en mente o simplemente quiera explorar posibilidades, nos encantaría saber de usted.',
    'blog.contactBtn': 'Contáctenos',
    'blog.viewProducts': 'Ver Productos',
    'contact.formName': 'Nombre',
    'contact.formEmail': 'Correo Electrónico',
    'contact.formCompany': 'Empresa',
    'contact.formSubject': 'Asunto',
    'contact.formMessage': 'Mensaje',
    'contact.formPlaceholderName': 'Su nombre',
    'contact.formPlaceholderEmail': 'su@email.com',
    'contact.formPlaceholderCompany': 'Nombre de su empresa',
    'contact.formPlaceholderSubject': '¿Cómo podemos ayudarle?',
    'contact.formPlaceholderMessage': 'Cuéntenos sobre sus requisitos de prendas de punto...',
    'contact.formSubmit': 'Enviar Mensaje',
    'contact.formSending': 'Enviando...',
    'contact.formRequired': 'es requerido',
    'contact.formInvalidEmail': 'Formato de correo inválido',
    'contact.thankYou': '¡Gracias!',
    'contact.thankYouMsg': 'Su mensaje ha sido enviado. Le responderemos dentro de 24 horas.',
    'contact.sendAnother': 'Enviar Otro Mensaje',
    'contact.infoTitle': 'Información de Contacto',
    'contact.address': 'Dirección',
    'contact.email': 'Correo Electrónico',
    'contact.phone': 'Teléfono',
    'contact.whatsapp': 'Chatear en WhatsApp',
    'contact.hours': 'Horario Comercial',
    'admin.title': 'Panel de Administración LINFAIR',
    'admin.viewSite': 'Ver Sitio',
    'admin.export': 'Exportar Datos',
    'admin.save': 'Guardar Cambios',
    'admin.saving': 'Guardando...',
    'admin.logout': 'Cerrar Sesión',
    'admin.tabProducts': 'Productos',
    'admin.tabBlog': 'Blog',
    'admin.tabContent': 'Contenido',
    'admin.tabInquiries': 'Consultas',
    'admin.reset': 'Restablecer',
    'admin.addProduct': '+ Añadir Producto',
    'admin.addBlog': '+ Añadir Artículo',
    'admin.saveSuccess': '¡Guardado exitosamente!',
    'admin.saveLocal': 'Guardado en almacenamiento local.',
    'admin.loading': 'Cargando...',
    'lang.en': 'English',
    'lang.es': 'Español',
    'lang.fr': 'Français',
    'lang.de': 'Deutsch',
    'lang.pt': 'Português',
  },

  fr: {
    'nav.home': 'Accueil',
    'nav.about': 'À Propos',
    'nav.products': 'Produits',
        'nav.blog': 'Blog',
    'nav.videos': 'Vidéos',
    'videos.heroTag': 'Galerie Vidéo',
    'videos.heroTitle': 'Découvrez Notre Savoir-Faire',
    'videos.heroDesc': 'Découvrez nos tricots premium en action - des présentations de produits à l\'artisanat derrière chaque pull.',
    'videos.all': 'Tout',
    'videos.product': 'Produit',
    'videos.brand': 'Marque',
    'videos.noVideos': 'Aucune vidéo disponible pour le moment. Revenez bientôt !',
    'videos.ctaTitle': 'Vous Voulez En Savoir Plus ?',
    'videos.ctaDesc': 'Contactez-nous pour les détails produits, les demandes en gros ou pour voir notre collection en personne.',
    'videos.contactBtn': 'Contactez-nous',
    'videos.viewProducts': 'Voir les Produits',
    'nav.contact': 'Contact',
    'nav.getQuote': 'Demander un Devis',
    'footer.quickLinks': 'Liens Rapides',
    'footer.collections': 'Collections',
    'footer.contact': 'Contact',
    'footer.rights': 'Tous droits réservés.',
    'footer.brandDesc': 'Fabricant de tricots premium dédié à la création de pulls, cardigans et hauts en maille exceptionnels pour l\'industrie mondiale de la mode.',
    'footer.menSweaters': 'Pulls Homme',
    'footer.womenSweaters': 'Pulls Femme',
    'footer.cashmere': 'Collection Cachemire',
    'footer.merino': 'Laine Mérinos',
    'home.featuredSubtitle': 'Collection Vedette',
    'home.featuredTitle': 'Nos Tricots Signature',
    'home.featuredDesc': 'Découvrez notre sélection curated de pulls en laine premium.',
    'home.viewAll': 'Voir Tous les Produits',
    'home.whyUs': 'Pourquoi LINFAIR',
    'home.whyUsTitle': 'Pourquoi Nous Choisir',
    'home.whyUsDesc': 'Ce qui distingue nos tricots.',
    'home.ctaTitle': 'Prêt à vous approvisionner en tricots premium ?',
    'home.ctaDesc': 'Partenaires avec LINFAIR pour votre prochaine collection. Contactez-nous pour une consultation et un devis.',
    'home.ctaBtn': 'Prenez Contact',
    'about.valuesSubtitle': 'Nos Valeurs',
    'about.valuesTitle': 'Ce Que Nous Défendons',
    'about.valuesDesc': 'Les principes qui guident chaque pull que nous fabriquons.',
    'about.timelineSubtitle': 'Notre Parcours',
    'about.timelineTitle': 'Étapes Clés',
    'about.timelineDesc': 'Moments clés de notre évolution en tant que fabricant de tricots premium.',
    'about.ctaTitle': 'Commencez Votre Partenariat',
    'about.ctaDesc': 'Créons des tricots exceptionnels pour votre marque. Contactez notre équipe.',
    'about.ctaBtn': 'Contactez-Nous',
    'products.heroSubtitle': 'Produits',
    'products.heroTitle': 'Nos Tricots',
    'products.heroHighlight': 'Collection',
    'products.heroDesc': 'Tricots premium pour femme conçus pour le confort et le style. Chaque pièce disponible en plusieurs couleurs.',
    'products.all': 'Tous',
    'products.inquire': 'Demander',
    'products.inquireAbout': 'S\'informer sur Ce Produit',
    'products.requestQuote': 'Demander un Devis',
    'products.specs': 'Spécifications',
    'products.video': 'Voir la Vidéo',
    'products.photos': 'Photos',
    'products.noProducts': 'Aucun produit trouvé dans cette catégorie.',
    'products.ctaTitle': 'Besoin de tricots personnalisés ?',
    'products.ctaDesc': 'Nous développons des pulls personnalisés selon les spécifications de votre marque. Créons quelque chose ensemble.',
    'products.ctaBtn': 'Demander un Devis',
    'products.articlesSubtitle': 'De Notre Blog',
    'products.articlesTitle': 'Derniers Articles',
    'products.viewAllArticles': 'Voir Tous les Articles',
    'products.readArticle': "Lire l'Article",
    'blog.heroSubtitle': 'Blog',
    'search.placeholder': 'Rechercher...',
    'search.products': 'Produits',
    'search.articles': 'Articles',
    'search.empty': 'Tapez pour rechercher des produits et des articles',
    'search.noResults': 'Aucun résultat trouvé',
    'blog.heroTitle': 'Perspectives et',
    'blog.heroHighlight': 'Tendances',
    'blog.heroDesc': 'Restez informé des dernières tendances de la mode tricot, des conseils d\'approvisionnement et des informations de l\'industrie de LINFAIR Wool.',
    'blog.readMore': 'Lire la Suite',
    'blog.ctaTitle': 'Restez Informé',
    'blog.ctaDesc': 'Abonnez-vous pour recevoir les dernières tendances en matière de tricots, des conseils d\'approvisionnement et des mises à jour de l\'entreprise directement dans votre boîte de réception.',
    'blog.ctaBtn': 'Contactez-Nous pour Vous Abonner',
    'blog.back': 'Retour au Blog',
    'blog.notFound': 'Article Non Trouvé',
    'blog.notFoundDesc': 'L\'article que vous recherchez n\'existe pas.',
    'blog.backBtn': 'Retour au Blog',
    'blog.relatedTitle': 'Intéressé à Travailler Avec Nous ?',
    'blog.relatedDesc': 'Que vous ayez un projet spécifique en tête ou que vous souhaitiez simplement explorer les possibilités, nous serions ravis de vous entendre.',
    'blog.contactBtn': 'Contactez-Nous',
    'blog.viewProducts': 'Voir les Produits',
    'contact.formName': 'Nom',
    'contact.formEmail': 'Email',
    'contact.formCompany': 'Entreprise',
    'contact.formSubject': 'Sujet',
    'contact.formMessage': 'Message',
    'contact.formPlaceholderName': 'Votre nom',
    'contact.formPlaceholderEmail': 'votre@email.com',
    'contact.formPlaceholderCompany': 'Nom de votre entreprise',
    'contact.formPlaceholderSubject': 'Comment pouvons-nous vous aider ?',
    'contact.formPlaceholderMessage': 'Parlez-nous de vos besoins en tricots...',
    'contact.formSubmit': 'Envoyer le Message',
    'contact.formSending': 'Envoi en cours...',
    'contact.formRequired': 'est requis',
    'contact.formInvalidEmail': 'Format d\'email invalide',
    'contact.thankYou': 'Merci !',
    'contact.thankYouMsg': 'Votre message a été envoyé. Nous vous répondrons sous 24 heures.',
    'contact.sendAnother': 'Envoyer un Autre Message',
    'contact.infoTitle': 'Informations de Contact',
    'contact.address': 'Adresse',
    'contact.email': 'Email',
    'contact.phone': 'Téléphone',
    'contact.whatsapp': 'Discuter sur WhatsApp',
    'contact.hours': 'Heures d\'Ouverture',
    'admin.title': 'Panneau d\'Administration LINFAIR',
    'admin.viewSite': 'Voir le Site',
    'admin.export': 'Exporter',
    'admin.save': 'Enregistrer',
    'admin.saving': 'Enregistrement...',
    'admin.logout': 'Déconnexion',
    'admin.tabProducts': 'Produits',
    'admin.tabBlog': 'Blog',
    'admin.tabContent': 'Contenu',
    'admin.tabInquiries': 'Demandes',
    'admin.reset': 'Réinitialiser',
    'admin.addProduct': '+ Ajouter Produit',
    'admin.addBlog': '+ Ajouter Article',
    'admin.saveSuccess': 'Enregistré avec succès !',
    'admin.saveLocal': 'Enregistré en local.',
    'admin.loading': 'Chargement...',
    'lang.en': 'English',
    'lang.es': 'Español',
    'lang.fr': 'Français',
    'lang.de': 'Deutsch',
    'lang.pt': 'Português',
  },

  de: {
    'nav.home': 'Startseite',
    'nav.about': 'Über Uns',
    'nav.products': 'Produkte',
        'nav.blog': 'Blog',
    'nav.videos': 'Videos',
    'videos.heroTag': 'Videogalerie',
    'videos.heroTitle': 'Sehen Sie Unser Handwerk in Bewegung',
    'videos.heroDesc': 'Sehen Sie unsere Premium-Strickwaren zum Leben erwachen - von Produktvorführungen bis zur Handwerkskunst hinter jedem Pullover.',
    'videos.all': 'Alle',
    'videos.product': 'Produkt',
    'videos.brand': 'Marke',
    'videos.noVideos': 'Noch keine Videos verfügbar. Schauen Sie bald wieder vorbei!',
    'videos.ctaTitle': 'Mehr Erfahren?',
    'videos.ctaDesc': 'Kontaktieren Sie uns für Produktdetails, Großhandelsanfragen oder um unsere Kollektion persönlich zu sehen.',
    'videos.contactBtn': 'Kontakt',
    'videos.viewProducts': 'Produkte Ansehen',
    'nav.contact': 'Kontakt',
    'nav.getQuote': 'Angebot Anfordern',
    'footer.quickLinks': 'Schnelllinks',
    'footer.collections': 'Kollektionen',
    'footer.contact': 'Kontakt',
    'footer.rights': 'Alle Rechte vorbehalten.',
    'footer.brandDesc': 'Premium-Strickwarenhersteller, der sich der Herstellung außergewöhnlicher Pullover, Cardigans und Strickoberteile für die globale Modebranche widmet.',
    'footer.menSweaters': 'Herrenpullover',
    'footer.womenSweaters': 'Damenpullover',
    'footer.cashmere': 'Kaschmir-Kollektion',
    'footer.merino': 'Merinowolle',
    'home.featuredSubtitle': 'Ausgewählte Kollektion',
    'home.featuredTitle': 'Unsere Signature-Strickwaren',
    'home.featuredDesc': 'Entdecken Sie unsere kuratierte Auswahl an Premium-Wollpullovern.',
    'home.viewAll': 'Alle Produkte Anzeigen',
    'home.whyUs': 'Warum LINFAIR',
    'home.whyUsTitle': 'Warum Uns Wählen',
    'home.whyUsDesc': 'Was unsere Strickwaren auszeichnet.',
    'home.ctaTitle': 'Bereit, Premium-Strickwaren zu beziehen?',
    'home.ctaDesc': 'Partner mit LINFAIR für Ihre nächste Kollektion. Kontaktieren Sie uns für eine Beratung und ein Angebot.',
    'home.ctaBtn': 'Kontakt Aufnehmen',
    'about.valuesSubtitle': 'Unsere Werte',
    'about.valuesTitle': 'Wofür Wir Stehen',
    'about.valuesDesc': 'Die Prinzipien, die jeden Pullover leiten, den wir herstellen.',
    'about.timelineSubtitle': 'Unsere Reise',
    'about.timelineTitle': 'Meilensteine',
    'about.timelineDesc': 'Schlüsselmomente in unserer Entwicklung als Premium-Strickwarenhersteller.',
    'about.ctaTitle': 'Starten Sie Ihre Partnerschaft',
    'about.ctaDesc': 'Lassen Sie uns außergewöhnliche Strickwaren für Ihre Marke kreieren. Kontaktieren Sie unser Team.',
    'about.ctaBtn': 'Kontaktieren Sie Uns',
    'products.heroSubtitle': 'Produkte',
    'products.heroTitle': 'Unsere Strickwaren',
    'products.heroHighlight': 'Kollektion',
    'products.heroDesc': 'Premium-Damenstrickwaren für Komfort und Stil gefertigt. Jedes Teil in mehreren Farben erhältlich.',
    'products.all': 'Alle',
    'products.inquire': 'Jetzt Anfragen',
    'products.inquireAbout': 'Zu Diesem Produkt Anfragen',
    'products.requestQuote': 'Angebot Anfordern',
    'products.specs': 'Spezifikationen',
    'products.video': 'Video Ansehen',
    'products.photos': 'Fotos',
    'products.noProducts': 'Keine Produkte in dieser Kategorie gefunden.',
    'products.ctaTitle': 'Benötigen Sie maßgeschneiderte Strickwaren?',
    'products.ctaDesc': 'Wir entwickeln maßgeschneiderte Pullover nach den Spezifikationen Ihrer Marke. Lassen Sie uns gemeinsam etwas schaffen.',
    'products.ctaBtn': 'Angebot Anfordern',
    'products.articlesSubtitle': 'Aus Unserem Blog',
    'products.articlesTitle': 'Neueste Artikel',
    'products.viewAllArticles': 'Alle Artikel Ansehen',
    'products.readArticle': 'Artikel Lesen',
    'blog.heroSubtitle': 'Blog',
    'search.placeholder': 'Suchen...',
    'search.products': 'Produkte',
    'search.articles': 'Artikel',
    'search.empty': 'Tippen Sie, um Produkte und Artikel zu suchen',
    'search.noResults': 'Keine Ergebnisse gefunden',
    'blog.heroTitle': 'Einblicke &',
    'blog.heroHighlight': 'Trends',
    'blog.heroDesc': 'Bleiben Sie informiert über die neuesten Strickmodetrends, Beschaffungstipps und Brancheneinblicke von LINFAIR Wool.',
    'blog.readMore': 'Weiterlesen',
    'blog.ctaTitle': 'Bleiben Sie auf dem Laufenden',
    'blog.ctaDesc': 'Abonnieren Sie, um die neuesten Strickmodetrends, Beschaffungstipps und Unternehmensupdates direkt in Ihren Posteingang zu erhalten.',
    'blog.ctaBtn': 'Kontaktieren Sie Uns zum Abonnieren',
    'blog.back': 'Zurück zum Blog',
    'blog.notFound': 'Beitrag Nicht Gefunden',
    'blog.notFoundDesc': 'Der gesuchte Blogbeitrag existiert nicht.',
    'blog.backBtn': 'Zurück zum Blog',
    'blog.relatedTitle': 'Interessiert an einer Zusammenarbeit?',
    'blog.relatedDesc': 'Egal, ob Sie ein bestimmtes Projekt im Kopf haben oder einfach nur Möglichkeiten erkunden möchten, wir freuen uns von Ihnen zu hören.',
    'blog.contactBtn': 'Kontaktieren Sie Uns',
    'blog.viewProducts': 'Produkte Anzeigen',
    'contact.formName': 'Name',
    'contact.formEmail': 'E-Mail',
    'contact.formCompany': 'Unternehmen',
    'contact.formSubject': 'Betreff',
    'contact.formMessage': 'Nachricht',
    'contact.formPlaceholderName': 'Ihr Name',
    'contact.formPlaceholderEmail': 'ihre@email.com',
    'contact.formPlaceholderCompany': 'Ihr Firmenname',
    'contact.formPlaceholderSubject': 'Wie können wir helfen?',
    'contact.formPlaceholderMessage': 'Erzählen Sie uns von Ihren Strickwarenanforderungen...',
    'contact.formSubmit': 'Nachricht Senden',
    'contact.formSending': 'Senden...',
    'contact.formRequired': 'ist erforderlich',
    'contact.formInvalidEmail': 'Ungültiges E-Mail-Format',
    'contact.thankYou': 'Vielen Dank!',
    'contact.thankYouMsg': 'Ihre Nachricht wurde gesendet. Wir werden uns innerhalb von 24 Stunden bei Ihnen melden.',
    'contact.sendAnother': 'Eine Weitere Nachricht Senden',
    'contact.infoTitle': 'Kontaktinformationen',
    'contact.address': 'Adresse',
    'contact.email': 'E-Mail',
    'contact.phone': 'Telefon',
    'contact.whatsapp': 'Chat auf WhatsApp',
    'contact.hours': 'Geschäftszeiten',
    'admin.title': 'LINFAIR Admin-Panel',
    'admin.viewSite': 'Seite Anzeigen',
    'admin.export': 'Daten Exportieren',
    'admin.save': 'Änderungen Speichern',
    'admin.saving': 'Speichern...',
    'admin.logout': 'Abmelden',
    'admin.tabProducts': 'Produkte',
    'admin.tabBlog': 'Blog',
    'admin.tabContent': 'Inhalt',
    'admin.tabInquiries': 'Anfragen',
    'admin.reset': 'Zurücksetzen',
    'admin.addProduct': '+ Produkt Hinzufügen',
    'admin.addBlog': '+ Artikel Hinzufügen',
    'admin.saveSuccess': 'Erfolgreich gespeichert!',
    'admin.saveLocal': 'Lokal gespeichert.',
    'admin.loading': 'Laden...',
    'lang.en': 'English',
    'lang.es': 'Español',
    'lang.fr': 'Français',
    'lang.de': 'Deutsch',
    'lang.pt': 'Português',
  },

  pt: {
    'nav.home': 'Início',
    'nav.about': 'Sobre',
    'nav.products': 'Produtos',
        'nav.blog': 'Blog',
    'nav.videos': 'Vídeos',
    'videos.heroTag': 'Galeria de Vídeos',
    'videos.heroTitle': 'Veja Nosso Ofício em Movimento',
    'videos.heroDesc': 'Veja nossos tricôs premium ganharem vida - de mostras de produtos ao artesanato por trás de cada suéter.',
    'videos.all': 'Todos',
    'videos.product': 'Produto',
    'videos.brand': 'Marca',
    'videos.noVideos': 'Nenhum vídeo disponível ainda. Volte em breve!',
    'videos.ctaTitle': 'Quer Saber Mais?',
    'videos.ctaDesc': 'Contate-nos para detalhes de produtos, consultas de atacado ou para ver nossa coleção pessoalmente.',
    'videos.contactBtn': 'Fale Conosco',
    'videos.viewProducts': 'Ver Produtos',
    'nav.contact': 'Contato',
    'nav.getQuote': 'Solicitar Orçamento',
    'footer.quickLinks': 'Links Rápidos',
    'footer.collections': 'Coleções',
    'footer.contact': 'Contato',
    'footer.rights': 'Todos os direitos reservados.',
    'footer.brandDesc': 'Fabricante premium de malhas dedicado a criar suéteres, cardigãs e tops de malha excepcionais para a indústria global da moda.',
    'footer.menSweaters': 'Suéteres Masculinos',
    'footer.womenSweaters': 'Suéteres Femininos',
    'footer.cashmere': 'Coleção Cashmere',
    'footer.merino': 'Lã Merino',
    'home.featuredSubtitle': 'Coleção em Destaque',
    'home.featuredTitle': 'Nossas Malhas Exclusivas',
    'home.featuredDesc': 'Explore nossa seleção curada de suéteres de lã premium.',
    'home.viewAll': 'Ver Todos os Produtos',
    'home.whyUs': 'Por que LINFAIR',
    'home.whyUsTitle': 'Por que nos Escolher',
    'home.whyUsDesc': 'O que torna nossas malhas especiais.',
    'home.ctaTitle': 'Pronto para adquirir malhas premium?',
    'home.ctaDesc': 'Faça parceria com a LINFAIR para sua próxima coleção. Entre em contato para uma consulta e orçamento.',
    'home.ctaBtn': 'Entre em Contato',
    'about.valuesSubtitle': 'Nossos Valores',
    'about.valuesTitle': 'O Que Defendemos',
    'about.valuesDesc': 'Os princípios que guiam cada suéter que fazemos.',
    'about.timelineSubtitle': 'Nossa Jornada',
    'about.timelineTitle': 'Marcos',
    'about.timelineDesc': 'Momentos-chave em nossa evolução como fabricante premium de malhas.',
    'about.ctaTitle': 'Inicie Sua Parceria',
    'about.ctaDesc': 'Vamos criar malhas excepcionais para sua marca. Entre em contato com nossa equipe.',
    'about.ctaBtn': 'Fale Conosco',
    'products.heroSubtitle': 'Produtos',
    'products.heroTitle': 'Nossas Malhas',
    'products.heroHighlight': 'Coleção',
    'products.heroDesc': 'Malhas premium femininas criadas para conforto e estilo. Cada peça disponível em várias cores.',
    'products.all': 'Todos',
    'products.inquire': 'Consultar Agora',
    'products.inquireAbout': 'Consultar Sobre Este Produto',
    'products.requestQuote': 'Solicitar Orçamento',
    'products.specs': 'Especificações',
    'products.video': 'Assistir Vídeo',
    'products.photos': 'Fotos',
    'products.noProducts': 'Nenhum produto encontrado nesta categoria.',
    'products.ctaTitle': 'Precisa de malhas personalizadas?',
    'products.ctaDesc': 'Desenvolvemos suéteres personalizados de acordo com as especificações da sua marca. Vamos criar algo juntos.',
    'products.ctaBtn': 'Solicitar Orçamento',
    'products.articlesSubtitle': 'Do Nosso Blog',
    'products.articlesTitle': 'Últimos Artigos',
    'products.viewAllArticles': 'Ver Todos os Artigos',
    'products.readArticle': 'Ler Artigo',
    'blog.heroSubtitle': 'Blog',
    'search.placeholder': 'Buscar...',
    'search.products': 'Produtos',
    'search.articles': 'Artigos',
    'search.empty': 'Digite para pesquisar produtos e artigos',
    'search.noResults': 'Nenhum resultado encontrado',
    'blog.heroTitle': 'Insights e',
    'blog.heroHighlight': 'Tendências',
    'blog.heroDesc': 'Mantenha-se informado com as últimas tendências da moda em malhas, dicas de fornecimento e insights do setor da LINFAIR Wool.',
    'blog.readMore': 'Ler Mais',
    'blog.ctaTitle': 'Fique por Dentro',
    'blog.ctaDesc': 'Inscreva-se para receber as últimas tendências em malhas, dicas de fornecimento e atualizações da empresa diretamente em sua caixa de entrada.',
    'blog.ctaBtn': 'Fale Conosco para se Inscrever',
    'blog.back': 'Voltar ao Blog',
    'blog.notFound': 'Post Não Encontrado',
    'blog.notFoundDesc': 'O post do blog que você está procurando não existe.',
    'blog.backBtn': 'Voltar ao Blog',
    'blog.relatedTitle': 'Interessado em Trabalhar Conosco?',
    'blog.relatedDesc': 'Quer você tenha um projeto específico em mente ou apenas queira explorar possibilidades, adoraríamos ouvir de você.',
    'blog.contactBtn': 'Fale Conosco',
    'blog.viewProducts': 'Ver Produtos',
    'contact.formName': 'Nome',
    'contact.formEmail': 'E-mail',
    'contact.formCompany': 'Empresa',
    'contact.formSubject': 'Assunto',
    'contact.formMessage': 'Mensagem',
    'contact.formPlaceholderName': 'Seu nome',
    'contact.formPlaceholderEmail': 'seu@email.com',
    'contact.formPlaceholderCompany': 'Nome da sua empresa',
    'contact.formPlaceholderSubject': 'Como podemos ajudar?',
    'contact.formPlaceholderMessage': 'Conte-nos sobre seus requisitos de malhas...',
    'contact.formSubmit': 'Enviar Mensagem',
    'contact.formSending': 'Enviando...',
    'contact.formRequired': 'é obrigatório',
    'contact.formInvalidEmail': 'Formato de e-mail inválido',
    'contact.thankYou': 'Obrigado!',
    'contact.thankYouMsg': 'Sua mensagem foi enviada. Responderemos dentro de 24 horas.',
    'contact.sendAnother': 'Enviar Outra Mensagem',
    'contact.infoTitle': 'Informações de Contato',
    'contact.address': 'Endereço',
    'contact.email': 'E-mail',
    'contact.phone': 'Telefone',
    'contact.whatsapp': 'Conversar no WhatsApp',
    'contact.hours': 'Horário Comercial',
    'admin.title': 'Painel de Administração LINFAIR',
    'admin.viewSite': 'Ver Site',
    'admin.export': 'Exportar Dados',
    'admin.save': 'Salvar Alterações',
    'admin.saving': 'Salvando...',
    'admin.logout': 'Sair',
    'admin.tabProducts': 'Produtos',
    'admin.tabBlog': 'Blog',
    'admin.tabContent': 'Conteúdo',
    'admin.tabInquiries': 'Consultas',
    'admin.reset': 'Restaurar',
    'admin.addProduct': '+ Adicionar Produto',
    'admin.addBlog': '+ Adicionar Artigo',
    'admin.saveSuccess': 'Salvo com sucesso!',
    'admin.saveLocal': 'Salvo no armazenamento local.',
    'admin.loading': 'Carregando...',
    'lang.en': 'English',
    'lang.es': 'Español',
    'lang.fr': 'Français',
    'lang.de': 'Deutsch',
    'lang.pt': 'Português',
    'lang.ru': 'Русский',
  },

  ru: {
    'nav.home': 'Главная',
    'nav.about': 'О нас',
    'nav.products': 'Продукция',
        'nav.blog': 'Блог',
    'nav.videos': 'Видео',
    'videos.heroTag': 'Видеогалерея',
    'videos.heroTitle': 'Наше Мастерство в Движении',
    'videos.heroDesc': 'Посмотрите, как наша премиальная вязаная одежда оживает - от демонстрации изделий до мастерства создания каждого свитера.',
    'videos.all': 'Все',
    'videos.product': 'Товар',
    'videos.brand': 'Бренд',
    'videos.noVideos': 'Видео пока нет. Загляните позже!',
    'videos.ctaTitle': 'Хотите Узнать Больше?',
    'videos.ctaDesc': 'Свяжитесь с нами по вопросам продукции, оптовых заказов или личного просмотра коллекции.',
    'videos.contactBtn': 'Связаться',
    'videos.viewProducts': 'Смотреть Товары',
    'nav.contact': 'Контакты',
    'nav.getQuote': 'Запросить цену',
    'footer.quickLinks': 'Быстрые ссылки',
    'footer.collections': 'Коллекции',
    'footer.contact': 'Контакты',
    'footer.rights': 'Все права защищены.',
    'footer.brandDesc': 'Производитель трикотажа премиум-класса, специализирующийся на создании исключительных свитеров, кардиганов и трикотажных топов для мировой индустрии моды.',
    'footer.menSweaters': 'Мужские свитера',
    'footer.womenSweaters': 'Женские свитера',
    'footer.cashmere': 'Кашемировая коллекция',
    'footer.merino': 'Мериносовая шерсть',
    'home.featuredSubtitle': 'Избранная коллекция',
    'home.featuredTitle': 'Наш фирменный трикотаж',
    'home.featuredDesc': 'Изучите нашу тщательно подобранную коллекцию свитеров из высококачественной шерсти.',
    'home.viewAll': 'Все товары',
    'home.whyUs': 'Почему LINFAIR',
    'home.whyUsTitle': 'Почему выбирают нас',
    'home.whyUsDesc': 'Что отличает наш трикотаж.',
    'home.ctaTitle': 'Готовы закупить трикотаж премиум-класса?',
    'home.ctaDesc': 'Станьте партнером LINFAIR для вашей следующей коллекции. Свяжитесь с нами для консультации и расчета стоимости.',
    'home.ctaBtn': 'Связаться с нами',
    'about.valuesSubtitle': 'Наши ценности',
    'about.valuesTitle': 'Наши принципы',
    'about.valuesDesc': 'Принципы, которыми мы руководствуемся при создании каждого свитера.',
    'about.timelineSubtitle': 'Наш путь',
    'about.timelineTitle': 'Вехи',
    'about.timelineDesc': 'Ключевые моменты нашего развития как производителя трикотажа премиум-класса.',
    'about.ctaTitle': 'Начните сотрудничество',
    'about.ctaDesc': 'Давайте создадим исключительный трикотаж для вашего бренда. Свяжитесь с нашей командой.',
    'about.ctaBtn': 'Свяжитесь с нами',
    'products.heroSubtitle': 'Продукция',
    'products.heroTitle': 'Наш трикотаж',
    'products.heroHighlight': 'Коллекция',
    'products.heroDesc': 'Женский трикотаж премиум-класса, созданный для комфорта и стиля. Каждое изделие доступно в нескольких цветах.',
    'products.all': 'Все',
    'products.inquire': 'Запросить',
    'products.inquireAbout': 'Запросить информацию о товаре',
    'products.requestQuote': 'Запросить цену',
    'products.specs': 'Характеристики',
    'products.video': 'Смотреть видео',
    'products.photos': 'Фото',
    'products.noProducts': 'В этой категории товары не найдены.',
    'products.ctaTitle': 'Нужен трикотаж на заказ?',
    'products.ctaDesc': 'Мы разрабатываем свитера по индивидуальным спецификациям вашего бренда. Давайте создадим что-то вместе.',
    'products.ctaBtn': 'Запросить цену',
    'products.articlesSubtitle': 'Из нашего блога',
    'products.articlesTitle': 'Последние статьи',
    'products.viewAllArticles': 'Смотреть все статьи',
    'products.readArticle': 'Читать статью',
    'blog.heroSubtitle': 'Блог',
    'search.placeholder': 'Поиск...',
    'search.products': 'Товары',
    'search.articles': 'Статьи',
    'search.empty': 'Введите для поиска товаров и статей',
    'search.noResults': 'Результатов не найдено',
    'blog.heroTitle': 'Идеи и',
    'blog.heroHighlight': 'Тренды',
    'blog.heroDesc': 'Будьте в курсе последних тенденций в мире трикотажной моды, советов по закупкам и отраслевых новостей от LINFAIR Wool.',
    'blog.readMore': 'Читать далее',
    'blog.ctaTitle': 'Будьте в курсе',
    'blog.ctaDesc': 'Подпишитесь, чтобы получать последние тенденции трикотажной моды, советы по закупкам и новости компании прямо на вашу почту.',
    'blog.ctaBtn': 'Свяжитесь с нами для подписки',
    'blog.back': 'Назад в блог',
    'blog.notFound': 'Статья не найдена',
    'blog.notFoundDesc': 'Статья, которую вы ищете, не существует.',
    'blog.backBtn': 'Назад в блог',
    'blog.relatedTitle': 'Заинтересованы в сотрудничестве?',
    'blog.relatedDesc': 'Если у вас есть конкретный проект или вы просто хотите изучить возможности, мы будем рады услышать вас.',
    'blog.contactBtn': 'Свяжитесь с нами',
    'blog.viewProducts': 'Посмотреть товары',
    'contact.formName': 'Имя',
    'contact.formEmail': 'Email',
    'contact.formCompany': 'Компания',
    'contact.formSubject': 'Тема',
    'contact.formMessage': 'Сообщение',
    'contact.formPlaceholderName': 'Ваше имя',
    'contact.formPlaceholderEmail': 'ваш@email.com',
    'contact.formPlaceholderCompany': 'Название компании',
    'contact.formPlaceholderSubject': 'Чем мы можем помочь?',
    'contact.formPlaceholderMessage': 'Расскажите о ваших потребностях в трикотаже...',
    'contact.formSubmit': 'Отправить',
    'contact.formSending': 'Отправка...',
    'contact.formRequired': 'обязательно',
    'contact.formInvalidEmail': 'Неверный формат email',
    'contact.thankYou': 'Спасибо!',
    'contact.thankYouMsg': 'Ваше сообщение отправлено. Мы ответим вам в течение 24 часов.',
    'contact.sendAnother': 'Отправить еще одно сообщение',
    'contact.infoTitle': 'Контактная информация',
    'contact.address': 'Адрес',
    'contact.email': 'Email',
    'contact.phone': 'Телефон',
    'contact.whatsapp': 'Чат в WhatsApp',
    'contact.hours': 'Часы работы',
    'admin.title': 'Панель управления LINFAIR',
    'admin.viewSite': 'На сайт',
    'admin.export': 'Экспорт',
    'admin.save': 'Сохранить',
    'admin.saving': 'Сохранение...',
    'admin.logout': 'Выйти',
    'admin.tabProducts': 'Товары',
    'admin.tabBlog': 'Блог',
    'admin.tabContent': 'Контент',
    'admin.tabInquiries': 'Запросы',
    'admin.reset': 'Сбросить',
    'admin.addProduct': '+ Добавить товар',
    'admin.addBlog': '+ Добавить статью',
    'admin.saveSuccess': 'Успешно сохранено!',
    'admin.saveLocal': 'Сохранено локально.',
    'admin.loading': 'Загрузка...',
    'lang.en': 'English',
    'lang.es': 'Español',
    'lang.fr': 'Français',
    'lang.de': 'Deutsch',
    'lang.pt': 'Português',
    'lang.ru': 'Русский',
  },
}

const LANG_VERSION = 'v5'

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>(() => {
    try {
      const saved = localStorage.getItem('linfair_lang')
      const ver = localStorage.getItem('linfair_lang_ver')
      if (ver === LANG_VERSION && (saved === 'en' || saved === 'es' || saved === 'fr' || saved === 'de' || saved === 'pt' || saved === 'ru')) {
        return saved
      }
    } catch {}
    // Default to English
    try {
      localStorage.setItem('linfair_lang', 'en')
      localStorage.setItem('linfair_lang_ver', LANG_VERSION)
    } catch {}
    return 'en'
  })

  const changeLang = useCallback((l: Lang) => {
    setLang(l)
    try {
      localStorage.setItem('linfair_lang', l)
      localStorage.setItem('linfair_lang_ver', LANG_VERSION)
    } catch {}
  }, [])

  const t = useCallback((key: string, vars?: Record<string, string | number>): string => {
    let text = translations[lang]?.[key] ?? translations.en[key] ?? key
    if (vars) {
      Object.entries(vars).forEach(([k, v]) => { text = text.replace(`{${k}}`, String(v)) })
    }
    return text
  }, [lang])

  return (
    <LangContext.Provider value={{ lang, setLang: changeLang, t }}>
      {children}
    </LangContext.Provider>
  )
}
